dimensions: 3
mesh_file: sphere_coarse.msh

train:
  epochs: 100
  batch_size: 32

# Optimizer:

optimizer: sgd
optimizer_kwargs:
   lr: 0.005
   weight_decay: 0.0001
   momentum: 0.9
   nesterov: False
scheduler: poly
